name=DC01
version=0.0.0
author=Steve Chong <steve.tm.chong@outlook.com>
maintainer=Steve Chong <steve.tm.chong@outlook.com>
sentence=Driver library for DC01 sensors.
paragraph=Driver library for DC01 to get sensor data for the environment.
category=Sensors
url=https://github.com/ctm6100/Arduino-DC01
architectures=*